config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:show, :edit, :update, :destroy] 

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'welcome#home'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

 belongs_to :user

  def self.create_with_omniauth(auth_hash)
    create! do |auth|
      auth.provider = auth_hash["provider"]
      auth.uid = auth_hash["uid"]
      auth.token = auth_hash["credentials"]["token"]
    end
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :authentications, :dependent => :destroy

  def self.create_with_auth_and_hash(authentication,auth_hash)
    # byebug
    create! do |u|
      u.first_name = auth_hash["info"]["first_name"]
      u.last_name = auth_hash["info"]["last_name"]
      u.birthday = auth_hash["extra"]["raw_info"]["birthday"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.password = SecureRandom.base64(8)
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

  def create_from_omniauth
    auth_hash = request.env["omniauth.auth"]

    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
    if authentication.user
      user = authentication.user 
      authentication.update_token(auth_hash)
      @next = root_url
      @notice = "Signed in!"
    else
      user = User.create_with_auth_and_hash(authentication,auth_hash)
      @next = root_url   
      @notice = "New user created"
    end
    sign_in(user)
    redirect_to @next, :notice => @notice
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def create
    # byebug
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :birthday, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user, only: [:home]
  
  def home
  end

  private

  def authenticate_user
    redirect_to sign_in_path if signed_out?
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <div id="user-widget">
    <% if current_user %>
      Welcome <strong><%= current_user.first_name %></strong>!
    <% else %>
      <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :birthday %>
  <%= form.date_select :birthday, type: 'date', start_year: 1900 %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>